# TNO Terminology Engine v2 configuration for the bron documentation.

scopedir: .
onNotExist: warn
output: .

mrgt:
  vsntag:

hrgt:
  converter[1]: markdown-table-row
  converter[2]: "{{#if glossaryAbbr}}| {{glossaryAbbr}} | Zie: [{{glossaryTerm}}](@) |\n{{/if}}"
  input:
    - "*.md"

trrt:
  converter: html-hovertext-link
  input:
    - "**/*.md"
