# TNO Terminology Engine v2 configuration for the bron documentation.

scopedir: .
onNotExist: warn
output: .

mrgt:
  vsntag:

hrgt:
  converter[1]: "| [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}}) | {{#if glossaryText}}{{noRefs glossaryText}}{{else}}Geen `glossaryText` opgegeven voor deze term.{{/if}} |\n"
  converter[2]: "{{#if glossaryAbbr}}| [{{glossaryAbbr}}]({{localize navurl}}) | Afkorting van [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}}). |\n{{else}}{{log level='silent'}}{{/if}}"
  input:
    - "*.md"

trrt:
  converter: html-hovertext-link
  input:
    - "**/*.md"
