# TNO Terminology Engine v2 configuration for the bron documentation.

scopedir: .
onNotExist: warn
output: .

mrgt:
  vsntag:

hrgt:
  converter[1]: "## [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n\n{{#if glossaryText}}{{glossaryText}}{{else}}Geen `glossaryText` opgegeven voor deze term.{{/if}}\n\n{{#if glossaryNotes}}### Notities\n\n{{#each glossaryNotes}}- {{this}}\n{{/each}}\n{{/if}}"
  converter[2]: "{{#if glossaryAbbr}}## [{{glossaryAbbr}}]({{localize navurl}})\n\nZie: [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{termid}}@)\n\n{{else}}{{log level='silent'}}{{/if}}"
  input:
    - "*.md"

trrt:
  converter: html-hovertext-link
  input:
    - "**/*.md"
